/**
 * AsteroidMiningModel.tsx
 * =======================
 * Interactive first-principles cost model for asteroid mining.
 * Computes $/kg of resource delivered to LEO as a function of
 * mission architecture and physical assumptions.
 *
 * Sections
 * --------
 *  1. Physical constants and propulsion presets
 *  2. Earth mining benchmarks (for comparison)
 *  3. Types and default parameter values
 *  4. Pure computation functions (no React)
 *      - computeMission()       per-asteroid mission cost + yield
 *      - computeFleetCurve()    $/kg vs fleet-size curve (N = 1..MAX_N)
 *  5. React component
 *      - State: model parameters (all sliders)
 *      - useMemo: delta-v sorted asteroid list (expensive, runs once)
 *      - useMemo: fleet curve (runs on every param change)
 *      - useEffect: renders Observable Plot charts
 *      - Render: stats, benchmark bar, slider panel, charts
 *
 * Data source
 * -----------
 * /thoughts/asteroid-mining/asteroid-data.json
 * Generated by scripts/build_website_data.py from JPL SBDB + Lowell AstOrb.
 * Schema: [a_au, e, i_deg, vol_m3, fam, dv_out_km_s, t_transfer_days]
 * Sorted ascending by dv_out_km_s (most accessible first).
 *
 * Assumptions (all exposed as sliders or noted in tech deep-dive):
 *  - Two-stage rocket equation: return propellant launched from Earth
 *  - Cargo loaded at asteroid (not launched from Earth)
 *  - Rendezvous at asteroid perihelion (lower bound on real delta-v)
 *  - No gravity assists; no ISRU propellant production
 *  - Plane change at aphelion of transfer orbit (single impulsive burn)
 */

import * as Plot from '@observablehq/plot';
import { useEffect, useMemo, useRef, useState } from 'react';
import './AsteroidMiningModel.css';

// ─────────────────────────────────────────────────────────────────────────────
// 1. PHYSICAL CONSTANTS
// ─────────────────────────────────────────────────────────────────────────────

/** Standard gravity [km/s²] — used to convert Isp → exhaust velocity */
const G0_KM_S2 = 9.80665e-3;

/**
 * Propulsion presets: label, specific impulse [s], effective exhaust velocity [km/s].
 *
 * Isp reference values are standard propulsion engineering figures.
 * Source: Sutton, G. P. & Biblarz, O. (2010). Rocket Propulsion Elements, 8th ed.
 * Wiley. [ref-16]
 *   – NTO/MMH: Table 5-5, ~300–340 s in vacuum
 *   – LOX/LH₂: Table 5-5, ~440–455 s in vacuum (RL-10 class)
 *   – Hall thruster: Chapter 17, ~1500–3000 s depending on power level
 */
const PROPULSION = {
  chemical_nto: {
    label: 'Chemical — NTO/MMH (Isp 320 s)',
    isp:   320,
    ve:    320 * G0_KM_S2,   // ≈ 3.14 km/s  [ref-16]
    note:  'Heritage propulsion (Dragon, many interplanetary probes). High thrust, short trip.',
  },
  chemical_lox: {
    label: 'Chemical — LOX/LH₂ (Isp 450 s)',
    isp:   450,
    ve:    450 * G0_KM_S2,   // ≈ 4.41 km/s  [ref-16]
    note:  'High-performance cryogenic. Better Isp but cryogen handling in deep space is complex.',
  },
  sep: {
    label: 'Solar Electric — Hall thruster (Isp 3000 s)',
    isp:   3000,
    ve:    3000 * G0_KM_S2,  // ≈ 29.4 km/s  [ref-16]
    note:  'Very high Isp; small dry mass needed for propellant. Low thrust → longer trip time (spiral, not Hohmann). Mission duration ×3–5 estimate applied.',
  },
} as const;
type PropulsionType = keyof typeof PROPULSION;

/** SEP missions take much longer due to low-thrust spiral trajectories.
 *  This multiplier approximates the trip-time penalty vs. ballistic Hohmann. */
const SEP_TIME_MULTIPLIER = 4.0;

/**
 * Mining throughput: bulk asteroid volume the spacecraft can excavate and
 * process per day [m³/day].  At 0.005 m³/day × 180 surface days = 0.9 m³
 * processed, which at unknown-family defaults (2,000 kg/m³, 10% metal,
 * 50% extraction efficiency) yields 0.9 × 2000 × 0.10 × 0.50 ≈ 90 kg — below
 * the 500 kg cargo cap, so density/fraction sliders directly control the output.
 *
 * This is a rough order-of-magnitude for a near-term robotic mining
 * system; no single citable benchmark exists yet for in-space mining rate.
 * Adjust via the surface-days slider to see throughput sensitivity.
 */
const MINING_RATE_M3_PER_DAY = 0.005;

// ─────────────────────────────────────────────────────────────────────────────
// 2. EARTH MINING BENCHMARKS  ($/kg, approximate 2024–2025)
// ─────────────────────────────────────────────────────────────────────────────

const METAL_BENCHMARKS = [
  // Prices in $/kg, spot mid-price, approximate 2024–2025.
  // Nickel & Cobalt: London Metal Exchange official prices [ref-10]
  // Platinum & Palladium: Johnson Matthey PGM market data [ref-11]
  { name: 'Nickel',    price: 16,      color: '#8da0cb', market: 'Earth mine', refId: 10 },
  { name: 'Cobalt',    price: 33,      color: '#66c2a5', market: 'Earth mine', refId: 10 },
  { name: 'Platinum',  price: 31_000,  color: '#e78ac3', market: 'Earth mine', refId: 11 },
  // Palladium collapsed from its 2022–23 highs (~$1,400/oz) to ~$1,000/oz
  // ($32K/kg) across 2024–25 as auto-catalyst demand softened. [ref-11]
  { name: 'Palladium', price: 32_000,  color: '#a6d854', market: 'Earth mine', refId: 11 },
];

/**
 * Water / propellant benchmarks for in-space resource economics.
 * These represent the estimated market price for water or propellant delivered
 * to LEO — the revenue target that asteroid-derived water must beat.
 *
 * Prices are indicative estimates for a nascent cislunar propellant market;
 * no spot market exists yet. Water at $1,250/kg and LOX/LH₂ at $900/kg
 * reflect the range discussed in commercial launch cost literature.
 * Derived from cost_model.py water mode benchmarks.
 */
const WATER_BENCHMARKS = [
  { name: 'LOX/LH₂ — LEO depot', price:   900, color: '#4fc3f7', market: 'LEO depot (est.)', refId: null },
  { name: 'Water — LEO depot',    price: 1_250, color: '#0288d1', market: 'LEO depot (est.)', refId: null },
];


// ─────────────────────────────────────────────────────────────────────────────
// 3. TYPES AND DEFAULT PARAMETER VALUES
// ─────────────────────────────────────────────────────────────────────────────

/** One row from asteroid-data.json */
type AsteroidRow = [
  number,  // 0  a_au
  number,  // 1  e
  number,  // 2  i_deg
  number,  // 3  vol_m3
  number,  // 4  fam  (0=primitive, 1=stony, 2=metal-rich, 3=unknown)
  number,  // 5  dv_out_km_s  (outbound-only; return handled by returnFactor)
  number,  // 6  t_transfer_days  (one-way transfer time)
];

/** All sliders / selectors that drive the cost model */
interface ModelParams {
  // Fleet
  fleetSize:       number;   // number of missions (top-N by accessibility)

  // Launch economics
  launchCostPerKg: number;   // $/kg to LEO

  // Spacecraft
  propulsion:      PropulsionType;
  dryMassKg:       number;   // spacecraft dry mass [kg]  (structure + propulsion + mining gear)
  cargoCapKg:      number;   // max resource mass per return trip [kg]

  // Operations
  opsPerDay:       number;   // $/day of active mission ops
  maxSurfaceDays:  number;   // hard upper bound on surface time (spacecraft endurance: power, consumables)

  // Program-level
  devCostM:        number;   // total spacecraft development cost [$M], amortized over fleet

  // Mining
  extractionEff:   number;   // fraction of available resource actually extracted (0–1)
  returnFactor:    number;   // return ΔV as a fraction of outbound ΔV (0 = full aerobraking, 1 = symmetric propulsive)
  contingency:     number;   // multiplier on computed ΔV (1.0 = no margin, 1.3 = 30% margin)

  // Per-family physical properties: [primitive, stony, metal-rich, unknown]
  densities:       [number, number, number, number];   // bulk density [kg/m³]
  metalFracs:      [number, number, number, number];   // metal resource mass fraction
}

const DEFAULT_PARAMS: ModelParams = {
  fleetSize:       10,
  launchCostPerKg: 2_720,  // Falcon 9 customer price ~$2,720/kg to LEO [ref-17]
  propulsion:      'chemical_nto',
  dryMassKg:       2_000,
  cargoCapKg:      500,
  opsPerDay:       50_000,
  maxSurfaceDays:  730,    // 2-year endurance cap; model will use less if cargo fills sooner
  devCostM:        500,
  extractionEff:   0.50,
  returnFactor:    0.60,
  contingency:     1.20,
  // Bulk (porosity-inclusive) densities from Carry (2012) [ref-15]:
  // C-complex 1,330±580, S-complex 2,720±540 kg/m³. Metal-rich/M-type bulk
  // clusters near ~3,500 kg/m³ in the density literature (well below solid-iron
  // grain density ~7,800 — M-types are porous). Unknown: conservative ~chondritic
  // bulk prior between the C and S complexes. Sliders allow pushing toward grain density.
  densities:   [1_300, 2_700, 3_500, 2_000],
  metalFracs:  [0.025, 0.12,  0.80,  0.10 ],
};

/** Result of a single-mission calculation */
interface MissionResult {
  launchCost:    number;   // $
  opsCost:       number;   // $
  devCostShare:  number;   // $
  totalCost:     number;   // $
  deliveredKg:   number;   // kg
  missionDays:   number;   // total days (transit + surface)
  surfaceDays:   number;   // actual mining time used (≤ maxSurfaceDays)
  wetMassKg:     number;   // launch mass [kg]
  dvTotalKmS:    number;   // total ΔV applied [km/s]
}

/** One point on the $/kg vs fleet-size curve */
interface CurvePoint {
  n:           number;   // fleet size
  costPerKg:   number;   // cumulative $/kg
  totalCost:   number;   // cumulative $
  totalDelivered: number;  // cumulative kg
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. PURE COMPUTATION FUNCTIONS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Compute all cost and yield figures for a single mission to one asteroid.
 *
 * Rocket equation (two-stage, because cargo is loaded at the asteroid):
 *
 *   m_prop_ret = (m_dry + m_cargo) × (exp(ΔV_ret / v_e) − 1)
 *   m_prop_out = (m_dry + m_prop_ret) × (exp(ΔV_out / v_e) − 1)
 *   m_wet      = m_dry + m_prop_out + m_prop_ret
 *
 * This correctly accounts for the outbound leg needing to carry the return
 * propellant (since all propellant is launched from Earth).
 */
function computeMission(
  asteroid: AsteroidRow,
  params: ModelParams,
): MissionResult {
  const {
    launchCostPerKg, propulsion, dryMassKg, cargoCapKg,
    opsPerDay, maxSurfaceDays, devCostM, fleetSize,
    extractionEff, returnFactor, contingency,
    densities, metalFracs,
  } = params;

  const [, , , vol_m3, fam, dv_out_raw, t_transfer] = asteroid;

  const ve = PROPULSION[propulsion].ve;

  // Apply contingency margin to delta-v
  const dv_out = dv_out_raw * contingency;
  const dv_ret = dv_out * returnFactor;

  // SEP missions spiral in/out: trip time is much longer than Hohmann
  const timeMultiplier = propulsion === 'sep' ? SEP_TIME_MULTIPLIER : 1.0;

  // ── Resource yield ──────────────────────────────────────────────────────
  //
  // Optimal surface time: mine until the cargo hold is full, then leave.
  // Staying longer adds ops cost with no extra cargo, so it is never optimal.
  // Two physical constraints cap the time before cargo is full:
  //   1. The asteroid may be too small to fill the hold at all.
  //   2. The spacecraft endurance (power, consumables) sets a hard ceiling.
  //
  //   grade [kg/m³]      = bulk density × resource mass fraction
  //   rateKgPerDay       = MINING_RATE_M3_PER_DAY × grade × extractionEff
  //   daysToFillCargo    = cargoCapKg / rateKgPerDay
  //   daysToMineAsteroid = vol_m3 / MINING_RATE_M3_PER_DAY
  //   surfaceDays        = min(daysToFillCargo, daysToMineAsteroid, maxSurfaceDays)
  //
  const density  = densities[fam];
  const fraction = metalFracs[fam];
  const grade    = density * fraction;   // kg of resource per m³ of bulk material
  const extractionRateKgPerDay = MINING_RATE_M3_PER_DAY * grade * extractionEff;
  const daysToFillCargo    = extractionRateKgPerDay > 0
    ? cargoCapKg / extractionRateKgPerDay
    : maxSurfaceDays;
  const daysToMineAsteroid = vol_m3 / MINING_RATE_M3_PER_DAY;
  const surfaceDays        = Math.min(daysToFillCargo, daysToMineAsteroid, maxSurfaceDays);

  const volumeProcessedM3 = Math.min(vol_m3, MINING_RATE_M3_PER_DAY * surfaceDays);
  const extractedKg  = volumeProcessedM3 * grade * extractionEff;
  const actualCargo  = Math.min(cargoCapKg, extractedKg);   // cargo-cap limited
  // Return / delivery efficiency is assumed 100% — no precedent exists for bulk
  // deep-space return losses, so we do not model a loss factor here.
  const deliveredKg  = actualCargo;

  const missionDays = 2 * t_transfer * timeMultiplier + surfaceDays;

  // ── Two-stage rocket equation ───────────────────────────────────────────
  //  Return leg first (loaded at asteroid, before departure):
  const m_prop_ret = (dryMassKg + actualCargo) * (Math.exp(dv_ret / ve) - 1);
  //  Outbound leg (must carry m_prop_ret from Earth):
  const m_prop_out = (dryMassKg + m_prop_ret)  * (Math.exp(dv_out / ve) - 1);
  const wetMassKg  = dryMassKg + m_prop_ret + m_prop_out;

  // ── Cost breakdown ──────────────────────────────────────────────────────
  const launchCost   = wetMassKg * launchCostPerKg;
  const opsCost      = opsPerDay * missionDays;
  const devCostShare = (devCostM * 1e6) / Math.max(1, fleetSize);
  const totalCost    = launchCost + opsCost + devCostShare;

  return {
    launchCost, opsCost, devCostShare, totalCost,
    deliveredKg, missionDays, surfaceDays, wetMassKg,
    dvTotalKmS: dv_out + dv_ret,
  };
}

/**
 * Compute the cumulative $/kg vs fleet-size curve.
 * Picks the top N asteroids (pre-sorted ascending by dv_out) and
 * accumulates cost and delivered mass.
 *
 * Only points 1..MAX_N are computed to keep the UI responsive.
 */
const MAX_CURVE_N = 200;

function computeFleetCurve(
  sortedAsteroids: AsteroidRow[],
  params: ModelParams,
): CurvePoint[] {
  const curve: CurvePoint[] = [];
  let totalMissionCost = 0;   // launch + ops only (variable costs)
  let totalDelivered   = 0;
  // Dev cost is a one-time fixed programme cost, paid once regardless of fleet
  // size and amortised across all missions.  It must NOT be multiplied by n
  // in the loop — otherwise changing the fleet-size slider reprices every point
  // on the curve and the axis rescales.
  const devCostTotal = params.devCostM * 1e6;
  const limit = Math.min(sortedAsteroids.length, MAX_CURVE_N);

  for (let n = 1; n <= limit; n++) {
    const res = computeMission(sortedAsteroids[n - 1], params);
    // Accumulate only the variable per-mission costs; add devCostTotal once below.
    totalMissionCost += res.launchCost + res.opsCost;
    totalDelivered   += res.deliveredKg;
    const totalCost = totalMissionCost + devCostTotal;
    curve.push({
      n,
      costPerKg:      totalDelivered > 0 ? totalCost / totalDelivered : Infinity,
      totalCost,
      totalDelivered,
    });
  }
  return curve;
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. REACT COMPONENT
// ─────────────────────────────────────────────────────────────────────────────

/** Format large dollar values compactly: $1.2M, $450K, $3.1B */
function formatDollars(v: number): string {
  if (!isFinite(v)) return '—';
  if (v >= 1e9)  return `$${(v / 1e9).toFixed(2)}B`;
  if (v >= 1e6)  return `$${(v / 1e6).toFixed(1)}M`;
  if (v >= 1e3)  return `$${(v / 1e3).toFixed(0)}K`;
  return `$${v.toFixed(0)}`;
}

function formatDollarPerKg(v: number): string {
  if (!isFinite(v) || v <= 0) return '—';
  if (v >= 1e6) return `$${(v / 1e6).toFixed(2)}M/kg`;
  if (v >= 1e3) return `$${(v / 1e3).toFixed(0)}K/kg`;
  return `$${v.toFixed(0)}/kg`;
}

function pct(n: number, total: number): number {
  return total > 0 ? Math.round((n / total) * 100) : 0;
}

/** Slider row helper */
function SliderRow({
  label, value, min, max, step, fmt, onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  fmt: (v: number) => string;
  onChange: (v: number) => void;
}) {
  return (
    <div className="amm-slider-row">
      <div className="amm-slider-header">
        <span className="amm-slider-name">{label}</span>
        <span className="amm-slider-value">{fmt(value)}</span>
      </div>
      <input
        type="range"
        className="amm-range"
        min={min} max={max} step={step}
        value={value}
        onChange={e => onChange(Number(e.target.value))}
      />
    </div>
  );
}

/** Metadata block exposed by asteroid-data.json (see build_website_data.py). */
interface AsteroidMeta {
  build_date?: string;
  count?: number;
  fam_counts?: Record<string, number>;
  taxonomy_sources?: {
    tier1_sbdb_spectral?:     number;
    tier2_mithneos_nir?:      number;
    tier3_neese_compilation?: number;
    tier4_sdss_photometric?:  number;
    tier5_unknown?:           number;
  };
}

export default function AsteroidMiningModel() {
  // ── Data state ────────────────────────────────────────────────────────────
  const [asteroids, setAsteroids]   = useState<AsteroidRow[] | null>(null);
  const [meta, setMeta]             = useState<AsteroidMeta | null>(null);
  const [loading, setLoading]       = useState(true);
  const [dataError, setDataError]   = useState<string | null>(null);

  // ── Model parameter state (one setter per param for slider simplicity) ───
  const [fleetSize,       setFleetSize]       = useState(DEFAULT_PARAMS.fleetSize);
  const [launchCostPerKg, setLaunchCostPerKg] = useState(DEFAULT_PARAMS.launchCostPerKg);
  const [propulsion,      setPropulsion]      = useState<PropulsionType>(DEFAULT_PARAMS.propulsion);
  const [dryMassKg,       setDryMassKg]       = useState(DEFAULT_PARAMS.dryMassKg);
  const [cargoCapKg,      setCargoCapKg]      = useState(DEFAULT_PARAMS.cargoCapKg);
  const [opsPerDay,        setOpsPerDay]        = useState(DEFAULT_PARAMS.opsPerDay);
  const [maxSurfaceDays,   setMaxSurfaceDays]   = useState(DEFAULT_PARAMS.maxSurfaceDays);
  const [devCostM,        setDevCostM]        = useState(DEFAULT_PARAMS.devCostM);
  const [extractionEff,   setExtractionEff]   = useState(DEFAULT_PARAMS.extractionEff);
  const [returnFactor,    setReturnFactor]    = useState(DEFAULT_PARAMS.returnFactor);
  const [contingency,     setContingency]     = useState(DEFAULT_PARAMS.contingency);

  // Advanced: per-family properties
  const [densities,     setDensities]     = useState<[number,number,number,number]>([...DEFAULT_PARAMS.densities]   as [number,number,number,number]);
  const [metalFracs,    setMetalFracs]    = useState<[number,number,number,number]>([...DEFAULT_PARAMS.metalFracs]   as [number,number,number,number]);
  // Water mode fracs: [primitive/C-type, stony, metal-rich, unknown]
  // CI/CM carbonaceous chondrites hold up to ~10–15% bound water by mass [ref-38];
  // 8% C-type default is mid-range. Stony and metal-rich are essentially dry.
  const [waterFracs,    setWaterFracs]    = useState<[number,number,number,number]>([0.08, 0.005, 0.001, 0.01]);

  // Resource mode: 'metal' = PGM/nickel economics; 'water' = propellant/water economics
  const [resourceMode,  setResourceMode]  = useState<'metal' | 'water'>('metal');

  // Chart DOM refs
  const curveRef    = useRef<HTMLDivElement>(null);
  const histRef     = useRef<HTMLDivElement>(null);
  /** Holds the Observable Plot SVG element so the dot-overlay effect can mutate it. */
  const chartElemRef = useRef<(Element & { scale?: (name: string) => { apply: (v: number) => number } }) | null>(null);

  // ── Load asteroid data ────────────────────────────────────────────────────
  useEffect(() => {
    fetch('/thoughts/asteroid-mining/asteroid-data.json')
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((d: { asteroids: AsteroidRow[]; meta?: AsteroidMeta }) => {
        setAsteroids(d.asteroids);
        setMeta(d.meta ?? null);
        setLoading(false);
      })
      .catch(err => {
        setDataError(String(err));
        setLoading(false);
      });
  }, []);

  // ── Assemble params object ─────────────────────────────────────────────
  // In water mode, metalFracs slot is filled with waterFracs so that computeMission
  // (which reads params.metalFracs for `fraction`) naturally uses water content.
  // The field name stays 'metalFracs' in the interface — we resolve which values to
  // use here at the params-assembly boundary.
  const params = useMemo<ModelParams>(() => ({
    fleetSize, launchCostPerKg, propulsion, dryMassKg, cargoCapKg,
    opsPerDay, maxSurfaceDays, devCostM, extractionEff,
    returnFactor, contingency,
    densities,
    metalFracs: resourceMode === 'water' ? waterFracs : metalFracs,
  }), [
    fleetSize, launchCostPerKg, propulsion, dryMassKg, cargoCapKg,
    opsPerDay, maxSurfaceDays, devCostM, extractionEff,
    returnFactor, contingency,
    densities, metalFracs, waterFracs, resourceMode,
  ]);

  // ── Fleet curve ───────────────────────────────────────────────────────────
  // fleetSize is intentionally excluded from deps: it only controls where the
  // red dot sits on the curve, not the curve's shape or the y-axis domain.
  // Excluding it means dragging the fleet-size slider never re-renders the chart.
  const fleetCurve = useMemo<CurvePoint[]>(() => {
    if (!asteroids) return [];
    return computeFleetCurve(asteroids, params);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    asteroids,
    launchCostPerKg, propulsion, dryMassKg, cargoCapKg,
    opsPerDay, maxSurfaceDays, devCostM,
    extractionEff, returnFactor, contingency,
    densities, metalFracs, waterFracs, resourceMode,
  ]);

  // ── Current fleet result (at selected fleet size) ─────────────────────
  const currentPoint = fleetSize > 0 && fleetCurve.length >= fleetSize
    ? fleetCurve[fleetSize - 1]
    : null;

  // ── Per-mission breakdown for the current fleet ───────────────────────
  const avgMission = useMemo(() => {
    if (!asteroids || !currentPoint) return null;
    // Average over the first fleetSize missions
    const slice = asteroids.slice(0, fleetSize);
    const results = slice.map(ast => computeMission(ast, params));
    const n = results.length;
    return {
      launchPct:       pct(results.reduce((s, r) => s + r.launchCost,   0), currentPoint.totalCost),
      opsPct:          pct(results.reduce((s, r) => s + r.opsCost,      0), currentPoint.totalCost),
      devPct:          pct(results.reduce((s, r) => s + r.devCostShare, 0), currentPoint.totalCost),
      avgDvKmS:        results.reduce((s, r) => s + r.dvTotalKmS,   0) / n,
      avgDays:         results.reduce((s, r) => s + r.missionDays,  0) / n,
      avgSurfaceDays:  results.reduce((s, r) => s + r.surfaceDays,  0) / n,
      avgWetMass:      results.reduce((s, r) => s + r.wetMassKg,    0) / n,
    };
  }, [asteroids, fleetSize, params, currentPoint]);

  // ── Benchmarks ────────────────────────────────────────────────────────
  const benchmarks = resourceMode === 'metal' ? METAL_BENCHMARKS : WATER_BENCHMARKS;
  const maxBenchmarkPrice = Math.max(...benchmarks.map(b => b.price));
  const currentCostPerKg  = currentPoint?.costPerKg ?? Infinity;

  // ── Effect 1: render base chart (curve + axis + benchmarks, NO red dot) ──
  // Dependencies deliberately exclude fleetSize so dragging the fleet slider
  // does NOT trigger a full chart redraw — only the dot overlay (Effect 2) updates.
  useEffect(() => {
    if (!curveRef.current || fleetCurve.length === 0) return;

    const validCurve = fleetCurve.filter(p => isFinite(p.costPerKg) && p.costPerKg > 0);
    if (validCurve.length === 0) return;

    // ── Fixed y-domain ───────────────────────────────────────────────────
    // yHi is anchored to fleet-of-1 cost so the curve always starts at the
    // top of the chart.  yLo is capped at 3.5 log-decades below yHi to
    // prevent cheap benchmarks (Ni $16) from compressing the curve, but
    // pulled down enough to include the most valuable benchmark (Pt/Pd).
    // This domain is FIXED while the fleet-size slider moves — only changes
    // when the curve itself changes (other sliders).
    const MAX_DECADES = 3.5;
    const yHi    = validCurve[0].costPerKg * 1.1;
    const yLoRaw = yHi / Math.pow(10, MAX_DECADES);
    const bmMax  = Math.max(...benchmarks.map(b => b.price));
    const yLo    = Math.min(yLoRaw, bmMax * 0.4);

    const bmVisible = benchmarks.filter(b => b.price >= yLo * 0.8);

    const w = curveRef.current.clientWidth || 480;
    curveRef.current.innerHTML = '';
    chartElemRef.current = null;

    const chart = Plot.plot({
      width: w,
      height: 280,
      marginLeft: 72,
      marginRight: 20,
      marginTop: 20,
      marginBottom: 50,
      y: {
        type: 'log',
        domain: [yLo, yHi],
        label: '$/kg to LEO',
        tickFormat: (d: number) =>
          d >= 1e6 ? `$${(d / 1e6).toFixed(1)}M` : d >= 1e3 ? `$${(d / 1e3).toFixed(0)}K` : `$${d}`,
      },
      x: { label: 'Fleet size (missions)', labelOffset: 36 },
      marks: [
        // Benchmark reference lines (only those within the visible domain)
        ...bmVisible.map(b =>
          Plot.ruleY([b.price], {
            stroke: b.color,
            strokeDasharray: '5,3',
            strokeWidth: 1.5,
          })
        ),
        // Benchmark labels at right edge
        ...bmVisible.map(b =>
          Plot.text([{ price: b.price, xpos: validCurve.length, label: b.name }], {
            x: 'xpos',
            y: 'price',
            text: 'label',
            textAnchor: 'end',
            dx: -4,
            dy: -6,
            fontSize: 9,
            fill: b.color,
          })
        ),
        // "Competitive" shading: green band below the highest visible benchmark
        ...(bmVisible.length > 0 ? [
          Plot.rectY(
            [{ x1: 0, x2: validCurve.length + 1, y1: yLo, y2: Math.max(...bmVisible.map(b => b.price)) }],
            { x1: 'x1', x2: 'x2', y1: 'y1', y2: 'y2', fill: '#2e9e6b', fillOpacity: 0.06 }
          ),
        ] : []),
        // Fleet curve
        Plot.line(validCurve, {
          x: 'n',
          y: 'costPerKg',
          stroke: '#496A81',
          strokeWidth: 2,
        }),
      ],
    });

    // Store the chart element so the dot-overlay effect can read its scales
    chartElemRef.current = chart as typeof chartElemRef.current;
    curveRef.current.appendChild(chart);
  }, [fleetCurve, benchmarks]);

  // ── Effect 2: overlay the red dot (no chart redraw) ───────────────────
  // Reads pixel coordinates from Observable Plot's scale API and directly
  // mutates the SVG — no innerHTML replacement, no axis flicker.
  useEffect(() => {
    const chart = chartElemRef.current;
    if (!chart) return;

    // Remove any previous dot overlay
    chart.querySelectorAll('.amm-dot-overlay').forEach(el => el.remove());

    const pt = fleetSize > 0 && fleetSize <= fleetCurve.length
      ? fleetCurve[fleetSize - 1]
      : null;
    if (!pt || !isFinite(pt.costPerKg) || pt.costPerKg <= 0) return;

    const xScale = chart.scale?.('x');
    const yScale = chart.scale?.('y');
    if (!xScale || !yScale) return;

    const cx = xScale.apply(pt.n);
    const cy = yScale.apply(pt.costPerKg);

    const label = pt.costPerKg >= 1e6
      ? `$${(pt.costPerKg / 1e6).toFixed(1)}M/kg`
      : pt.costPerKg >= 1e3
        ? `$${(pt.costPerKg / 1e3).toFixed(0)}K/kg`
        : `$${pt.costPerKg.toFixed(0)}/kg`;

    const ns = 'http://www.w3.org/2000/svg';
    const g = document.createElementNS(ns, 'g');
    g.setAttribute('class', 'amm-dot-overlay');

    const circle = document.createElementNS(ns, 'circle');
    circle.setAttribute('cx', String(cx));
    circle.setAttribute('cy', String(cy));
    circle.setAttribute('r', '6');
    circle.setAttribute('fill', '#e63946');
    g.appendChild(circle);

    const text = document.createElementNS(ns, 'text');
    text.setAttribute('x', String(cx));
    text.setAttribute('y', String(cy - 10));
    text.setAttribute('text-anchor', 'middle');
    text.setAttribute('font-size', '9');
    text.setAttribute('fill', '#e63946');
    text.textContent = label;
    g.appendChild(text);

    chart.appendChild(g);
  }, [fleetSize, fleetCurve]);

  // Delta-v histogram
  useEffect(() => {
    if (!histRef.current || !asteroids) return;
    const limit = Math.min(asteroids.length, MAX_CURVE_N);
    const allDvs  = asteroids.slice(0, limit).map(r => ({ dv: r[5], selected: false }));
    const selDvs  = asteroids.slice(0, fleetSize).map(r => ({ dv: r[5], selected: true  }));

    // Fleet cutoff: ΔV of the last selected asteroid (or last available if fleet > data)
    const cutoffIdx = Math.min(fleetSize, asteroids.length) - 1;
    const cutoffDv  = cutoffIdx >= 0 ? asteroids[cutoffIdx][5] : null;

    const w = histRef.current.clientWidth || 480;
    histRef.current.innerHTML = '';

    const chart = Plot.plot({
      width: w,
      height: 180,
      marginLeft: 48,
      marginTop: 28,
      x: { label: 'Outbound ΔV (km/s)' },
      y: { label: 'Count' },
      marks: [
        Plot.rectY(
          allDvs,
          Plot.binX({ y: 'count' }, { x: 'dv', thresholds: 40, fill: '#c6cde8', stroke: 'white', strokeWidth: 0.5 })
        ),
        Plot.rectY(
          selDvs,
          Plot.binX({ y: 'count' }, { x: 'dv', thresholds: 40, fill: '#496A81', stroke: 'white', strokeWidth: 0.5 })
        ),
        // Vertical cutoff line at the ΔV of the Nth (last selected) asteroid
        ...(cutoffDv !== null ? [
          Plot.ruleX([cutoffDv], { stroke: '#c0392b', strokeWidth: 1.5, strokeDasharray: '4,3' }),
          Plot.text([cutoffDv], {
            x: cutoffDv,
            frameAnchor: 'top',
            dy: 10,
            text: () => `fleet cutoff · ${cutoffDv.toFixed(1)} km/s`,
            fill: '#c0392b',
            fontSize: 9.5,
            textAnchor: 'middle',
          }),
        ] : []),
      ],
    });
    histRef.current.appendChild(chart);
  }, [asteroids, fleetSize]);

  // ── Render ────────────────────────────────────────────────────────────────
  if (loading) return <div className="amm-loading">Loading asteroid dataset…</div>;
  if (dataError) return <div className="amm-loading">Error loading data: {dataError}</div>;

  const famNames = ['Primitive / carbonaceous', 'Ordinary stony', 'Metal-rich / iron', 'Unknown'];

  return (
    <div className="amm-outer">

      {/* ── Stat cards ─────────────────────────────────────────────────── */}
      <div className="amm-stats">
        <div className="amm-stat-card">
          <div className="amm-stat-label">Cost to deliver 1 kg to LEO</div>
          <div className="amm-stat-value">{formatDollarPerKg(currentCostPerKg)}</div>
          <div className="amm-stat-sub">
            Fleet of {fleetSize} mission{fleetSize !== 1 ? 's' : ''}
          </div>
        </div>
        <div className="amm-stat-card">
          <div className="amm-stat-label">Total fleet cost</div>
          <div className="amm-stat-value">{formatDollars(currentPoint?.totalCost ?? 0)}</div>
          <div className="amm-stat-sub">
            {formatDollars((currentPoint?.totalCost ?? 0) / Math.max(1, fleetSize))}/mission avg
          </div>
        </div>
        <div className="amm-stat-card">
          <div className="amm-stat-label">Total mass delivered</div>
          <div className="amm-stat-value">
            {currentPoint
              ? currentPoint.totalDelivered >= 1e3
                ? `${(currentPoint.totalDelivered / 1e3).toFixed(1)} t`
                : `${currentPoint.totalDelivered.toFixed(0)} kg`
              : '—'}
          </div>
          <div className="amm-stat-sub">
            {resourceMode === 'metal' ? 'Metal feedstock' : 'Water / propellant'}
            {' · '}
            {avgMission ? `avg ${avgMission.avgDvKmS.toFixed(1)} km/s ΔV` : ''}
          </div>
        </div>
      </div>

      {/* ── Cost breakdown bar ─────────────────────────────────────────── */}
      {avgMission && (
        <div className="amm-breakdown-row">
          <div className="amm-breakdown-bar">
            <div style={{ width: `${avgMission.launchPct}%`, background: '#496A81' }} title={`Launch: ${avgMission.launchPct}%`} />
            <div style={{ width: `${avgMission.opsPct}%`,   background: '#8da0cb' }} title={`Ops: ${avgMission.opsPct}%`} />
            <div style={{ width: `${avgMission.devPct}%`,   background: '#c6cde8' }} title={`Dev: ${avgMission.devPct}%`} />
          </div>
          <div className="amm-breakdown-legend">
            <span><i style={{ background: '#496A81' }} />Launch {avgMission.launchPct}%</span>
            <span><i style={{ background: '#8da0cb' }} />Ops {avgMission.opsPct}%</span>
            <span><i style={{ background: '#c6cde8' }} />Dev {avgMission.devPct}%</span>
          </div>
        </div>
      )}

      {/* ── Earth benchmark comparison ──────────────────────────────────── */}
      <div className="amm-benchmark-section">
        <div className="amm-benchmark-label">
          {resourceMode === 'metal'
            ? 'Earth mining comparison (commodity spot price)'
            : 'Propellant market comparison (LEO depot price, estimated)'}
        </div>
        {benchmarks.map(b => {
          const logMax = Math.log10(Math.max(maxBenchmarkPrice, currentCostPerKg) * 1.5);
          const logMin = Math.log10(Math.min(...benchmarks.map(x => x.price)) * 0.5);
          const toX = (v: number) => isFinite(v) && v > 0
            ? Math.min(100, Math.max(0, ((Math.log10(v) - logMin) / (logMax - logMin)) * 100))
            : 0;
          const fillPct    = toX(b.price);
          const currentPct = toX(currentCostPerKg);
          return (
            <div key={b.name} className="amm-benchmark-item">
              <span className="amm-benchmark-name">{b.name}</span>
              <div className="amm-benchmark-track">
                <div
                  className="amm-benchmark-fill"
                  style={{ width: `${fillPct}%`, background: b.color }}
                />
                {isFinite(currentCostPerKg) && (
                  <div
                    className="amm-current-marker"
                    style={{ left: `${currentPct}%` }}
                    title={`Model: ${formatDollarPerKg(currentCostPerKg)}`}
                  />
                )}
              </div>
              <span className="amm-benchmark-num">
                {b.price >= 1000
                  ? `$${(b.price / 1000).toFixed(0)}K/kg`
                  : `$${b.price}/kg`}
              </span>
            </div>
          );
        })}
        {isFinite(currentCostPerKg) && (
          <div style={{ fontSize: 11, marginTop: '0.5em', color: 'rgb(96,115,159)' }}>
            ● Red marker = model result ({formatDollarPerKg(currentCostPerKg)})
            {resourceMode === 'metal' && currentCostPerKg < 31_000 && (
              <span style={{ color: '#2e9e6b', marginLeft: 8 }}>
                ✓ Below platinum price — economically viable if metal-rich asteroid
              </span>
            )}
            {resourceMode === 'water' && currentCostPerKg < 1_250 && (
              <span style={{ color: '#2e9e6b', marginLeft: 8 }}>
                ✓ Below LEO depot water price — propellant mining may be viable
              </span>
            )}
          </div>
        )}
        <div className="amm-cite-note">
          {resourceMode === 'metal' ? (
            <>Ni/Co prices: <a href="#ref-10">London Metal Exchange</a> [10] · Pt/Pd prices:{' '}
            <a href="#ref-11">Johnson Matthey PGM data</a> [11] · Spot mid-price, approx. 2024–2025.</>
          ) : (
            <>Water/propellant prices are indicative estimates for a nascent cislunar propellant
            market; no public spot market exists. Figures derived from launch cost modeling literature.</>
          )}
        </div>
      </div>

      {/* ── Main body: sliders + charts ────────────────────────────────── */}
      <div className="amm-body">

        {/* ── Slider panel ──────────────────────────────────────────────── */}
        <div className="amm-sliders">

          {/* Resource mode toggle */}
          <div style={{ display: 'flex', gap: 6, marginBottom: '1.25em' }}>
            {(['metal', 'water'] as const).map(mode => (
              <button
                key={mode}
                onClick={() => setResourceMode(mode)}
                style={{
                  flex: 1,
                  padding: '0.5em 0',
                  border: `1.5px solid ${resourceMode === mode ? '#496A81' : 'rgb(229,233,240)'}`,
                  borderRadius: 6,
                  background: resourceMode === mode ? '#496A81' : 'transparent',
                  color: resourceMode === mode ? '#fff' : 'rgb(96,115,159)',
                  fontSize: 12,
                  fontWeight: resourceMode === mode ? 600 : 400,
                  cursor: 'pointer',
                  lineHeight: 1.4,
                }}
              >
                {mode === 'metal' ? '⚙ Metals / PGMs' : '💧 Water / Propellant'}
              </button>
            ))}
          </div>
          {resourceMode === 'water' && (
            <div style={{
              background: 'rgba(2,136,209,0.07)',
              border: '1px solid rgba(2,136,209,0.25)',
              borderRadius: 6,
              padding: '0.55em 0.8em',
              fontSize: 11,
              color: 'rgb(2,136,209)',
              marginBottom: '1em',
              lineHeight: 1.45,
            }}>
              <strong>Water / propellant mode:</strong> Resource fractions now represent water content
              by mass. C-type (primitive) asteroids are the primary targets — the most hydrous carbonaceous
              chondrites (CI/CM) hold up to ~10–15% structurally-bound water. Benchmarks show estimated LEO
              depot prices, not Earth commodity prices.
            </div>
          )}

          {/* Fleet */}
          <div className="amm-section-title">Fleet</div>
          <SliderRow
            label="Fleet size (missions)"
            value={fleetSize} min={1} max={150} step={1}
            fmt={v => `${v} missions`}
            onChange={setFleetSize}
          />

          {/* Launch — log-scale slider with reference benchmarks */}
          <div className="amm-section-title">Launch economics</div>
          {(() => {
            // Log-scale mapping: $10 → pos 0, $3000 → pos 1000
            const LOG_MIN = Math.log10(10);
            const LOG_MAX = Math.log10(3000);
            const toPos  = (v: number) => Math.round(((Math.log10(Math.max(10, Math.min(3000, v))) - LOG_MIN) / (LOG_MAX - LOG_MIN)) * 1000);
            const toVal  = (pos: number) => {
              const raw = Math.pow(10, LOG_MIN + (pos / 1000) * (LOG_MAX - LOG_MIN));
              // Round to 1 sig-fig steps appropriate to the magnitude
              if (raw < 50)   return Math.round(raw);
              if (raw < 200)  return Math.round(raw / 10)  * 10;
              if (raw < 1000) return Math.round(raw / 50)  * 50;
              return              Math.round(raw / 100) * 100;
            };
            const refs = [
              { price: 10,   label: '$10/kg',    sub: 'SpaceX aspirational', refId: null },
              { price: 100,  label: '~$100/kg',  sub: 'Starship (est.)',     refId: 18   },
              { price: 2720, label: '$2,720/kg', sub: 'Falcon 9',            refId: 17   },
            ] as const;
            return (
              <div className="amm-slider-row">
                <div className="amm-slider-header">
                  <span className="amm-slider-name">Launch price to LEO</span>
                  <span className="amm-slider-value">${launchCostPerKg.toLocaleString()}/kg</span>
                </div>
                <input
                  type="range"
                  className="amm-range"
                  min={0} max={1000} step={1}
                  value={toPos(launchCostPerKg)}
                  onChange={e => setLaunchCostPerKg(toVal(Number(e.target.value)))}
                />
                <div className="amm-launch-refs">
                  {refs.map(({ price, label, sub, refId }) => {
                    const pct = ((Math.log10(price) - LOG_MIN) / (LOG_MAX - LOG_MIN)) * 100;
                    const xShift = pct < 10 ? '0%' : pct > 90 ? '-100%' : '-50%';
                    return (
                      <div key={price} className="amm-launch-ref-marker" style={{ left: `${pct}%`, transform: `translateX(${xShift})`, textAlign: pct < 10 ? 'left' : pct > 90 ? 'right' : 'center' }}>
                        <div className="amm-launch-ref-tick" />
                        <div className="amm-launch-ref-label">
                          {label}
                          {refId && <a href={`#ref-${refId}`}>[{refId}]</a>}
                        </div>
                        <div className="amm-launch-ref-sub">{sub}</div>
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })()}

          {/* Spacecraft */}
          <div className="amm-section-title">Spacecraft</div>
          <div className="amm-slider-row">
            <div className="amm-slider-header">
              <span className="amm-slider-name">Propulsion</span>
            </div>
            <select
              className="amm-select"
              value={propulsion}
              onChange={e => setPropulsion(e.target.value as PropulsionType)}
            >
              {Object.entries(PROPULSION).map(([k, v]) => (
                <option key={k} value={k}>{v.label}</option>
              ))}
            </select>
            <div style={{ fontSize: 10.5, color: 'rgb(96,115,159)', marginTop: 4 }}>
              {PROPULSION[propulsion].note}
            </div>
          </div>
          {/* Spacecraft dry mass — reference ticks from real asteroid missions */}
          {(() => {
            // Lower bound lowered to 400 kg so Hayabusa2 (493 kg dry) sits just inside range.
            // Upper bound: no well-cited precedent; 10,000 kg is aspirational.
            const DM_MIN = 400;
            const DM_MAX = 10_000;
            const toPct = (v: number) => ((v - DM_MIN) / (DM_MAX - DM_MIN)) * 100;
            const refs = [
              // OSIRIS-REx dry mass: 880 kg (launch mass 2,110 kg − ~1,230 kg propellant) [ref-20]
              { mass: 880,   label: '880 kg',   sub: 'OSIRIS-REx',    refId: 20 },
              // Psyche dry mass: ~1,616 kg per JPL (launch 2,747 kg − 1,085 kg Xe, less rounding) [ref-21]
              { mass: 1_616, label: '1,616 kg', sub: 'Psyche (dry)',   refId: 21 },
              // Cargo Dragon 1 dry mass: ~4,200 kg (capsule + trunk, no propellant/cargo) [ref-22]
              { mass: 4_200, label: '~4,200 kg', sub: 'Cargo Dragon 1', refId: 22 },
            ] as const;
            return (
              <div className="amm-slider-row">
                <div className="amm-slider-header">
                  <span className="amm-slider-name">Spacecraft dry mass</span>
                  <span className="amm-slider-value">{dryMassKg.toLocaleString()} kg</span>
                </div>
                <input
                  type="range" className="amm-range"
                  min={DM_MIN} max={DM_MAX} step={100}
                  value={dryMassKg}
                  onChange={e => setDryMassKg(Number(e.target.value))}
                />
                <div className="amm-launch-refs">
                  {refs.map(({ mass, label, sub, refId }) => (
                    <div key={mass} className="amm-launch-ref-marker" style={{ left: `${toPct(mass)}%` }}>
                      <div className="amm-launch-ref-tick" />
                      <div className="amm-launch-ref-label">
                        {label}<a href={`#ref-${refId}`}>[{refId}]</a>
                      </div>
                      <div className="amm-launch-ref-sub">{sub}</div>
                    </div>
                  ))}
                </div>
                <div style={{ fontSize: 10.5, color: 'rgb(96,115,159)', marginTop: 4, lineHeight: 1.4 }}>
                  Lower anchor: Hayabusa2 dry ~493 kg<a href="#ref-19" style={{ color: 'rgb(96,115,159)' }}>[19]</a> — smallest real asteroid mission, no mining hardware. Mass above ~1,700 kg ≈ mining hardware budget. No well-cited upper bound exists.
                </div>
              </div>
            );
          })()}

          {/* Return cargo capacity — Dragon as the only demonstrated large Earth-return ref */}
          {(() => {
            const CC_MIN = 10;
            const CC_MAX = 5_000;
            const toPct = (v: number) => ((v - CC_MIN) / (CC_MAX - CC_MIN)) * 100;
            const refs = [
              // Cargo Dragon return down-mass: ~3,000 kg (Dragon 1); Cargo Dragon 2 ≈ 2,500 kg.
              // LEO → Earth only; still the only vehicle returning bulk pressurized cargo intact. [ref-22]
              { mass: 3_000, label: '~3,000 kg', sub: 'Cargo Dragon', refId: 22 },
            ] as const;
            return (
              <div className="amm-slider-row">
                <div className="amm-slider-header">
                  <span className="amm-slider-name">Return cargo capacity</span>
                  <span className="amm-slider-value">{cargoCapKg.toLocaleString()} kg</span>
                </div>
                <input
                  type="range" className="amm-range"
                  min={CC_MIN} max={CC_MAX} step={10}
                  value={cargoCapKg}
                  onChange={e => setCargoCapKg(Number(e.target.value))}
                />
                <div className="amm-launch-refs">
                  {refs.map(({ mass, label, sub, refId }) => (
                    <div key={mass} className="amm-launch-ref-marker" style={{ left: `${toPct(mass)}%` }}>
                      <div className="amm-launch-ref-tick" />
                      <div className="amm-launch-ref-label">
                        {label}<a href={`#ref-${refId}`}>[{refId}]</a>
                      </div>
                      <div className="amm-launch-ref-sub">{sub}</div>
                    </div>
                  ))}
                </div>
                <div style={{ fontSize: 10.5, color: 'rgb(96,115,159)', marginTop: 4, lineHeight: 1.4 }}>
                  No deep-space bulk return precedent. OSIRIS-REx<a href="#ref-20" style={{ color: 'rgb(96,115,159)' }}>[20]</a> — the largest asteroid sample ever — returned 121.6 g from Bennu. Dragon<a href="#ref-22" style={{ color: 'rgb(96,115,159)' }}>[22]</a> shown for LEO scale only; deep-space return capsule design is an open engineering problem.
                </div>
              </div>
            );
          })()}

          {/* Hardware ratio consistency check */}
          {(() => {
            const ratio = dryMassKg / Math.max(1, cargoCapKg);
            // Dragon (capsule only, no mining hardware): ~4,200 kg dry / ~3,000 kg cargo ≈ 1.4×
            const DRAGON_RATIO = 4_200 / 3_000;
            const miningHardwareKg = Math.max(0, dryMassKg - cargoCapKg * DRAGON_RATIO);
            const isInsane = cargoCapKg > dryMassKg;
            const isTight  = ratio < DRAGON_RATIO && !isInsane;
            return (
              <div style={{
                background: isInsane ? '#fff3cd' : isTight ? '#fff3cd' : '#f8f9fb',
                border: `1px solid ${isInsane || isTight ? '#ffc107' : 'rgb(229,233,240)'}`,
                borderRadius: 6,
                padding: '0.6em 0.8em',
                fontSize: 11.5,
                marginBottom: '0.75em',
                lineHeight: 1.5,
              }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.25em' }}>
                  <span style={{ color: 'rgb(96,115,159)', textTransform: 'uppercase', fontSize: 10, letterSpacing: '0.05em' }}>
                    Hardware ratio (dry ÷ cargo)
                  </span>
                  <span style={{ fontWeight: 700, color: isInsane || isTight ? '#664d03' : 'var(--accent, #496A81)' }}>
                    {ratio.toFixed(1)}×
                  </span>
                </div>
                {isInsane ? (
                  <span style={{ color: '#664d03' }}>
                    ⚠ Cargo ({cargoCapKg.toLocaleString()} kg) exceeds dry mass — physically implausible. A return capsule must weigh more than its cargo.
                  </span>
                ) : isTight ? (
                  <span style={{ color: '#664d03' }}>
                    ⚠ Below Dragon's ratio (1.4×) — Dragon carries no mining hardware at all. A mining spacecraft needs structure, excavation, processing, and power systems on top of the return vehicle mass.
                  </span>
                ) : (
                  <span style={{ color: 'rgb(96,115,159)' }}>
                    Dragon (no mining hardware) is 1.4×. Your extra {miningHardwareKg.toLocaleString(undefined, {maximumFractionDigits: 0})} kg above Dragon scale ≈ your mining hardware budget.
                  </span>
                )}
              </div>
            );
          })()}

          {/* Mission */}
          <div className="amm-section-title">Mission</div>
          {/* Mining equipment endurance — reference ticks from rover design lives */}
          {(() => {
            const SD_MIN = 30;
            const SD_MAX = 1095;
            const toPct = (v: number) => ((v - SD_MIN) / (SD_MAX - SD_MIN)) * 100;
            const refs = [
              // MER Spirit & Opportunity design life: 90 sols. Opportunity lasted 5,352 sols (~14.5 yr). [ref-13]
              { days: 90,  label: '90 d',  sub: 'MER design life',          refId: 13 },
              // Curiosity & Perseverance prime mission: 1 Mars year ≈ 687 Earth days. Curiosity still active. [ref-37]
              { days: 687, label: '687 d', sub: 'Curiosity/Percy design life', refId: 37 },
            ] as const;
            return (
              <div className="amm-slider-row">
                <div className="amm-slider-header">
                  <span className="amm-slider-name">Mining equipment endurance (max surface time)</span>
                  <span className="amm-slider-value">{maxSurfaceDays} days ({(maxSurfaceDays / 365).toFixed(1)} yr)</span>
                </div>
                <input
                  type="range" className="amm-range"
                  min={SD_MIN} max={SD_MAX} step={10}
                  value={maxSurfaceDays}
                  onChange={e => setMaxSurfaceDays(Number(e.target.value))}
                />
                <div className="amm-launch-refs">
                  {refs.map(({ days, label, sub, refId }) => (
                    <div key={days} className="amm-launch-ref-marker" style={{ left: `${toPct(days)}%` }}>
                      <div className="amm-launch-ref-tick" />
                      <div className="amm-launch-ref-label">
                        {label}<a href={`#ref-${refId}`}>[{refId}]</a>
                      </div>
                      <div className="amm-launch-ref-sub">{sub}</div>
                    </div>
                  ))}
                </div>
                <div style={{ fontSize: 10.5, color: 'rgb(96,115,159)', marginTop: 4, marginBottom: 8, lineHeight: 1.4 }}>
                  Hard ceiling on mining operations — but note the distinction between two very different
                  endurance limits. <strong>Spacecraft bus</strong> (electronics, power, comms): routinely
                  exceeds design life by 5–20×. MER Opportunity was designed for 90 sols; it reached sol 5,352.
                  Curiosity was designed for ~687 Earth days; it has passed 4,000 sols. The electronics are not the
                  binding constraint.{' '}
                  <strong>Excavation hardware</strong> is: drill bits, conveyor mechanisms, and seals that
                  experience real mechanical wear with no servicing possible. No space precedent exists for
                  autonomous mining equipment running beyond a few hours. Terrestrial mining drills require
                  maintenance every few hundred hours. This slider therefore represents <em>mining subsystem</em>{' '}
                  endurance, not spacecraft lifetime. The model mines only as long as needed to fill the
                  cargo hold — actual surface time is shown in the mission profile.
                </div>
              </div>
            );
          })()}
          {/* ΔV contingency margin — ESA margin philosophy reference ticks */}
          {(() => {
            const C_MIN = 1.0;
            const C_MAX = 2.0;
            const toPct = (v: number) => ((v - C_MIN) / (C_MAX - C_MIN)) * 100;
            const refs = [
              // ESA: 5% margin on deterministic (accurately-calculated) trajectory manoeuvres
              // at a mature design stage [ref-29]
              { val: 1.05, label: '×1.05', sub: 'ESA deterministic ΔV', refId: 29 },
              // 20%: ESA's early-phase system-level (dry-mass) margin, used here as a
              // conservative ΔV-contingency proxy — not an ESA-stated ΔV margin. [ref-29]
              { val: 1.20, label: '×1.20', sub: 'Early-phase margin',  refId: 29 },
            ] as const;
            return (
              <div className="amm-slider-row">
                <div className="amm-slider-header">
                  <span className="amm-slider-name">ΔV contingency margin</span>
                  <span className="amm-slider-value">×{contingency.toFixed(2)}</span>
                </div>
                <input
                  type="range" className="amm-range"
                  min={C_MIN} max={C_MAX} step={0.05}
                  value={contingency}
                  onChange={e => setContingency(Number(e.target.value))}
                />
                <div className="amm-launch-refs">
                  {refs.map(({ val, label, sub, refId }) => (
                    <div key={val} className="amm-launch-ref-marker" style={{ left: `${toPct(val)}%` }}>
                      <div className="amm-launch-ref-tick" />
                      <div className="amm-launch-ref-label">
                        {label}<a href={`#ref-${refId}`}>[{refId}]</a>
                      </div>
                      <div className="amm-launch-ref-sub">{sub}</div>
                    </div>
                  ))}
                </div>
                <div style={{ fontSize: 10.5, color: 'rgb(96,115,159)', marginTop: 4, lineHeight: 1.4 }}>
                  Multiplier applied to the Hohmann ΔV to account for trajectory corrections, navigation
                  errors, and unmodelled perturbations. ESA<a href="#ref-29" style={{ color: 'rgb(96,115,159)' }}>[29]</a> specifies 5% on
                  deterministic (accurately-calculated) manoeuvres at a mature design stage; its 20% figure is a
                  system-level dry-mass margin, used here as a conservative ΔV-contingency proxy rather than an
                  ESA-stated ΔV margin. The stronger justification for a large margin: real NEA mission ΔV budgets
                  typically exceed Hohmann minima by 20–100%<a href="#ref-12" style={{ color: 'rgb(96,115,159)' }}>[12]</a><a href="#ref-14" style={{ color: 'rgb(96,115,159)' }}>[14]</a> due to launch-window constraints.
                </div>
              </div>
            );
          })()}

          {/* Return ΔV factor — Sonter (1997) aerobraking vs propulsive reference */}
          {(() => {
            const RF_MIN = 0.0;
            const RF_MAX = 1.0;
            const toPct = (v: number) => v * 100;
            const refs = [
              // Sonter (1997) Table 2: "NEA to Earth transfer orbit ≈ 1.0 km/s" vs
              // "LEO to Near Earth Asteroid ≈ 5.5 km/s" → ratio ≈ 0.18.
              // This is the asteroid-departure ΔV only; Earth capture is free via aerobraking. [ref-14]
              { val: 0.18, label: '~0.18×', sub: 'Aerobrake at Earth', refId: 14 },
            ] as const;
            return (
              <div className="amm-slider-row">
                <div className="amm-slider-header">
                  <span className="amm-slider-name">Return ΔV factor</span>
                  <span className="amm-slider-value">
                    {returnFactor === 0 ? '0 (full aerobrake)' : returnFactor === 1.0 ? '1.0 (propulsive)' : returnFactor.toFixed(2)}
                  </span>
                </div>
                <input
                  type="range" className="amm-range"
                  min={RF_MIN} max={RF_MAX} step={0.05}
                  value={returnFactor}
                  onChange={e => setReturnFactor(Number(e.target.value))}
                />
                <div className="amm-launch-refs">
                  {refs.map(({ val, label, sub, refId }) => (
                    <div key={val} className="amm-launch-ref-marker" style={{ left: `${toPct(val)}%` }}>
                      <div className="amm-launch-ref-tick" />
                      <div className="amm-launch-ref-label">
                        {label}<a href={`#ref-${refId}`}>[{refId}]</a>
                      </div>
                      <div className="amm-launch-ref-sub">{sub}</div>
                    </div>
                  ))}
                </div>
                <div style={{ fontSize: 10.5, color: 'rgb(96,115,159)', marginTop: 4, lineHeight: 1.4 }}>
                  Return ΔV as a fraction of outbound ΔV. From Sonter (1997)<a href="#ref-14" style={{ color: 'rgb(96,115,159)' }}>[14]</a>, the
                  asteroid-departure (Earth-return injection) ΔV is ~1–2 km/s against an outbound ~5.5–6 km/s, so the
                  ratio works out to ~0.17–0.36 with Earth aerobraking providing free capture (~0.18 is the optimistic
                  1 ÷ 5.5 end, a derived figure rather than a Sonter-stated ratio). At 1.0×, full propulsive Earth
                  capture is required, consuming otherwise-saleable return cargo as reaction mass.
                </div>
              </div>
            );
          })()}

          {/* Program costs */}
          <div className="amm-section-title">Program costs</div>

          {/* Daily operations cost — real NASA mission ops budgets as anchors */}
          {(() => {
            const OPS_MIN = 5_000;
            const OPS_MAX = 500_000;
            const toPct = (v: number) => ((v - OPS_MIN) / (OPS_MAX - OPS_MIN)) * 100;
            const refs = [
              // Spitzer: ~$14M/yr ÷ 365 ≈ $38K/day (retired 2020) [ref-27]
              { perDay: 38_400,  label: '~$38K/day',  sub: 'Spitzer',  refId: 27 },
              // Chandra: ~$68M/yr recent operating budget ÷ 365 ≈ $186K/day [ref-26]
              // (NASA's FY2025 proposal to cut this to ~$41M was deemed unworkable.)
              { perDay: 186_000, label: '~$186K/day', sub: 'Chandra',  refId: 26 },
              // Hubble: ~$93.8M/yr avg ÷ 365 ≈ $257K/day [ref-26]
              { perDay: 257_000, label: '~$257K/day', sub: 'Hubble',   refId: 26 },
            ] as const;
            return (
              <div className="amm-slider-row">
                <div className="amm-slider-header">
                  <span className="amm-slider-name">Daily operations cost</span>
                  <span className="amm-slider-value">${(opsPerDay / 1000).toFixed(0)}K/day</span>
                </div>
                <input
                  type="range" className="amm-range"
                  min={OPS_MIN} max={OPS_MAX} step={5_000}
                  value={opsPerDay}
                  onChange={e => setOpsPerDay(Number(e.target.value))}
                />
                <div className="amm-launch-refs">
                  {refs.map(({ perDay, label, sub, refId }) => (
                    <div key={perDay} className="amm-launch-ref-marker" style={{ left: `${toPct(perDay)}%` }}>
                      <div className="amm-launch-ref-tick" />
                      <div className="amm-launch-ref-label">
                        {label}<a href={`#ref-${refId}`}>[{refId}]</a>
                      </div>
                      <div className="amm-launch-ref-sub">{sub}</div>
                    </div>
                  ))}
                </div>
                <div style={{ fontSize: 10.5, color: 'rgb(96,115,159)', marginTop: 4, lineHeight: 1.4 }}>
                  Lower end: Voyager 1&amp;2 combined ~$12K/day<a href="#ref-25" style={{ color: 'rgb(96,115,159)' }}>[25]</a> — a 2–3 person team on a 50-year-old mission. A deep-space mining operation would need flight ops, ground control, and engineering support.
                </div>
              </div>
            );
          })()}

          {/* Development cost — NASA mission class caps as anchors */}
          {(() => {
            const DEV_MIN = 50;
            const DEV_MAX = 10_000;  // $10B ceiling, accommodates JWST at $8.8B
            const toPct = (v: number) => ((v - DEV_MIN) / (DEV_MAX - DEV_MIN)) * 100;
            const fmtCost = (m: number) => m >= 1_000 ? `$${(m / 1_000).toFixed(1)}B` : `$${m}M`;
            const refs = [
              // NASA Discovery class cost cap: ~$500M (spacecraft dev, excl. launch) [ref-23]
              { costM: 500,   label: '$500M',  sub: 'Discovery cap',     refId: 23 },
              // NASA New Frontiers cost cap: ~$900M (spacecraft dev, excl. launch) [ref-23]
              { costM: 900,   label: '$900M',  sub: 'New Frontiers cap', refId: 23 },
              // JWST total development: ~$8.8B (2003–2021) [ref-24]
              { costM: 8_800, label: '$8.8B',  sub: 'JWST',              refId: 24 },
            ] as const;
            return (
              <div className="amm-slider-row">
                <div className="amm-slider-header">
                  <span className="amm-slider-name">Development cost (total)</span>
                  <span className="amm-slider-value">{fmtCost(devCostM)}</span>
                </div>
                <input
                  type="range" className="amm-range"
                  min={DEV_MIN} max={DEV_MAX} step={50}
                  value={devCostM}
                  onChange={e => setDevCostM(Number(e.target.value))}
                />
                <div className="amm-launch-refs">
                  {refs.map(({ costM, label, sub, refId }) => (
                    <div key={costM} className="amm-launch-ref-marker" style={{ left: `${toPct(costM)}%` }}>
                      <div className="amm-launch-ref-tick" />
                      <div className="amm-launch-ref-label">
                        {label}<a href={`#ref-${refId}`}>[{refId}]</a>
                      </div>
                      <div className="amm-launch-ref-sub">{sub}</div>
                    </div>
                  ))}
                </div>
                <div style={{ fontSize: 10.5, color: 'rgb(96,115,159)', marginTop: 4, lineHeight: 1.4 }}>
                  OSIRIS-REx spacecraft dev: $589M (New Frontiers class)<a href="#ref-20" style={{ color: 'rgb(96,115,159)' }}>[20]</a>.
                  Launch cost is handled by the slider above, not included here.
                </div>
              </div>
            );
          })()}

          {/* Mining */}
          <div className="amm-section-title">Mining efficiency</div>
          {(() => {
            const EFF_MIN = 0.05;
            const EFF_MAX = 0.99;
            const toPct = (v: number) => ((v - EFF_MIN) / (EFF_MAX - EFF_MIN)) * 100;
            // Terrestrial ore processing benchmarks from Wills & Finch (2016) [ref-28]
            const refs = [
              // Copper heap leaching: 70–80% recovery, median ~75%
              { eff: 0.75, label: '~75%', sub: 'Cu heap leach', refId: 28 },
              // Nickel sulfide froth flotation: 85–92% recovery, median ~88%
              { eff: 0.88, label: '~88%', sub: 'Ni flotation',  refId: 28 },
            ] as const;
            return (
              <div className="amm-slider-row">
                <div className="amm-slider-header">
                  <span className="amm-slider-name">Processing recovery yield</span>
                  <span className="amm-slider-value">{Math.round(extractionEff * 100)}%</span>
                </div>
                <input
                  type="range" className="amm-range"
                  min={EFF_MIN} max={EFF_MAX} step={0.01}
                  value={extractionEff}
                  onChange={e => setExtractionEff(Number(e.target.value))}
                />
                <div className="amm-launch-refs">
                  {refs.map(({ eff, label, sub, refId }) => (
                    <div key={eff} className="amm-launch-ref-marker" style={{ left: `${toPct(eff)}%` }}>
                      <div className="amm-launch-ref-tick" />
                      <div className="amm-launch-ref-label">
                        {label}<a href={`#ref-${refId}`}>[{refId}]</a>
                      </div>
                      <div className="amm-launch-ref-sub">{sub}</div>
                    </div>
                  ))}
                </div>
                <div style={{ fontSize: 10.5, color: 'rgb(96,115,159)', marginTop: 4, lineHeight: 1.4 }}>
                  Fraction of the resource in processed material that is successfully extracted.
                  Terrestrial hydrometallurgical benchmarks shown for reference — no in-space analog exists.
                  Space conditions (microgravity, vacuum, uncharacterised regolith mineralogy) introduce
                  significant additional uncertainty. Return and delivery efficiency is assumed 100%.
                </div>
              </div>
            );
          })()}

          {/* Per-family material properties — always visible */}
          <div className="amm-section-title">
            Per-family material properties
          </div>
          <div className="amm-advanced-panel" style={{ borderTop: 'none', marginTop: 0, paddingTop: 0 }}>
            <div style={{ fontSize: 11, color: 'rgb(96,115,159)', marginBottom: '0.5em' }}>
              {(() => {
                // Dynamic taxonomy coverage from asteroid-data.json metadata.
                // Sources: SBDB spec_B/spec_T (highest confidence) → MITHNEOS NIR
                // → Neese 2010 compilation → SDSS photometric → unknown.
                const fc = meta?.fam_counts;
                const total = fc
                  ? (fc['0'] ?? 0) + (fc['1'] ?? 0) + (fc['2'] ?? 0) + (fc['3'] ?? 0)
                  : (asteroids?.length ?? 0);
                const unknown = fc?.['3'] ?? 0;
                const classified = total - unknown;
                if (total === 0) {
                  return 'Adjust the Unknown row to capture your taxonomic assumption.';
                }
                const knownPct = (classified / total) * 100;
                const unkPct   = (unknown    / total) * 100;
                const sources  = meta?.taxonomy_sources;
                const breakdown = sources
                  ? ` (sources: SBDB spec ${sources.tier1_sbdb_spectral ?? 0}, ` +
                    `MITHNEOS ${sources.tier2_mithneos_nir ?? 0}, ` +
                    `Neese ${sources.tier3_neese_compilation ?? 0}, ` +
                    `SDSS ${sources.tier4_sdss_photometric ?? 0})`
                  : '';
                return (
                  `${knownPct.toFixed(0)}% of asteroids in this dataset have a taxonomy assignment` +
                  `${breakdown}. The remaining ${unkPct.toFixed(0)}% are "unknown" — ` +
                  `adjust the Unknown row to capture your assumption.`
                );
              })()}
            </div>
            {famNames.map((name, fi) => (
              <div key={fi} className="amm-family-row">
                <div className="amm-family-label">{name}</div>
                <div className="amm-family-inputs">
                  <label>
                    Density: {densities[fi].toLocaleString()} kg/m³
                    <input type="range" min={500} max={9000} step={100}
                      value={densities[fi]}
                      onChange={e => setDensities(prev => {
                        const n = [...prev] as [number,number,number,number];
                        n[fi] = Number(e.target.value); return n;
                      })} />
                  </label>
                  {resourceMode === 'metal' ? (
                    <label>
                      Metal frac: {(metalFracs[fi] * 100).toFixed(1)}%
                      <input type="range" min={0} max={0.99} step={0.001}
                        value={metalFracs[fi]}
                        onChange={e => {
                          const val = Number(e.target.value);
                          setMetalFracs(prev => { const n = [...prev] as [number,number,number,number]; n[fi] = val; return n; });
                        }} />
                    </label>
                  ) : (
                    <label>
                      Water frac: {(waterFracs[fi] * 100).toFixed(2)}%
                      <input type="range" min={0} max={0.30} step={0.001}
                        value={waterFracs[fi]}
                        onChange={e => {
                          const val = Number(e.target.value);
                          setWaterFracs(prev => { const n = [...prev] as [number,number,number,number]; n[fi] = val; return n; });
                        }} />
                    </label>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ── Chart panel ───────────────────────────────────────────────── */}
        <div className="amm-charts">
          <div className="amm-chart-box">
            <div className="amm-chart-title">
              {resourceMode === 'metal' ? '$/kg metal to LEO vs fleet size' : '$/kg water/propellant to LEO vs fleet size'}
            </div>
            <div ref={curveRef} />
            <div className="amm-chart-note">
              {(() => {
                const valid = fleetCurve.filter(p => isFinite(p.costPerKg) && p.costPerKg > 0);
                if (valid.length < 2) return null;

                const first   = valid[0].costPerKg;
                const last    = valid[valid.length - 1].costPerKg;
                const factor  = first / last;

                // Replicate the domain logic from the chart useEffect to identify
                // which benchmarks are off-screen (so we can name them in text)
                const bmMax     = Math.max(...benchmarks.map(b => b.price));
                const yHi       = valid[0].costPerKg * 1.1;
                const yLoRaw    = yHi / Math.pow(10, 3.5);
                const yLo       = Math.min(yLoRaw, bmMax * 0.4);
                const bmBelow   = benchmarks.filter(b => b.price < yLo * 0.8);

                // How far above the most valuable benchmark is the current cost?
                const topBm     = benchmarks.reduce((a, b) => b.price > a.price ? b : a);
                const gapFactor = currentCostPerKg / topBm.price;

                return (
                  <>
                    Fleet picks the N most accessible asteroids (lowest outbound ΔV).
                    Green band = competitive zone (below highest benchmark).
                    {' '}Red dot = current selection
                    {' '}({factor >= 2 ? `${factor.toFixed(1)}× cheaper at N=${valid.length} vs N=1` : 'little fleet scaling at these settings'}).
                    {isFinite(gapFactor) && gapFactor > 1 && (
                      <> Currently <strong>{gapFactor.toFixed(0)}×</strong> above {topBm.name} price.</>
                    )}
                    {bmBelow.length > 0 && (
                      <> Benchmarks off-chart (below domain): {bmBelow.map(b => `${b.name} ($${b.price}/kg)`).join(', ')}.</>
                    )}
                  </>
                );
              })()}
            </div>
          </div>

          <div className="amm-chart-box">
            <div className="amm-chart-title">Outbound ΔV distribution (accessible NEA pool)</div>
            <div ref={histRef} />
            <div className="amm-chart-note">
              Light blue = first {Math.min(MAX_CURVE_N, asteroids?.length ?? 0)} asteroids with known diameter.
              Dark blue = selected fleet of {fleetSize}.
              ΔV computed via Hohmann transfer to perihelion × {contingency.toFixed(2)} contingency margin.
            </div>
          </div>

          {avgMission && (
            <div className="amm-chart-box">
              <div className="amm-chart-title">Average mission profile (fleet of {fleetSize})</div>
              <table style={{ width: '100%', fontSize: 12, borderCollapse: 'collapse' }}>
                <tbody>
                  {[
                    ['Avg mission ΔV (total)',    `${avgMission.avgDvKmS.toFixed(2)} km/s`],
                    ['Avg launch mass (wet)',     `${avgMission.avgWetMass.toFixed(0)} kg`],
                    ['Avg mission duration',      `${Math.round(avgMission.avgDays)} days (${(avgMission.avgDays / 365).toFixed(1)} yr)`],
                    ['Avg surface / mining time', `${Math.round(avgMission.avgSurfaceDays)} days — optimal (cap: ${maxSurfaceDays} days)`],
                    ['Propulsion (v_e)',          `${PROPULSION[propulsion].ve.toFixed(2)} km/s  (Isp ${PROPULSION[propulsion].isp} s)`],
                    ['Avg cost / mission',        formatDollars((currentPoint?.totalCost ?? 0) / Math.max(1, fleetSize))],
                    ['Avg yield / mission',       `${((currentPoint?.totalDelivered ?? 0) / Math.max(1, fleetSize)).toFixed(1)} kg delivered`],
                  ].map(([k, v]) => (
                    <tr key={String(k)} style={{ borderBottom: '1px solid rgb(229,233,240)' }}>
                      <td style={{ padding: '0.35em 0.5em', color: 'rgb(96,115,159)' }}>{k}</td>
                      <td style={{ padding: '0.35em 0.5em', fontWeight: 600, textAlign: 'right' }}>{v}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>

      <div style={{ fontSize: 10.5, color: 'rgb(96,115,159)', marginTop: '1em', lineHeight: 1.5 }}>
        <strong>Data:</strong> {asteroids?.length.toLocaleString()} NEAs from JPL SBDB + Lowell AstOrb with known diameter.
        ΔV = Hohmann to perihelion + Oberth departure + inclination plane-change.
        See the Technical Deep Dive section below for full equation derivation.
      </div>
    </div>
  );
}
